export const JOB_TITLES = [
  'Software Engineer',
  'Senior Software Engineer',
  'Staff Software Engineer',
  'Principal Engineer',
  'Frontend Developer',
  'Backend Developer',
  'Full Stack Developer',
  'Web Developer',
  'Mobile Developer',
  'iOS Developer',
  'Android Developer',
  'React Developer',
  'Node.js Developer',
  'Python Developer',
  'Java Developer',
  'Go Developer',
  'Rust Developer',
  'DevOps Engineer',
  'Site Reliability Engineer',
  'Cloud Engineer',
  'Platform Engineer',
  'Infrastructure Engineer',
  'Data Engineer',
  'Data Analyst',
  'Data Scientist',
  'Machine Learning Engineer',
  'AI Engineer',
  'MLOps Engineer',
  'QA Engineer',
  'Test Engineer',
  'Automation Engineer',
  'Security Engineer',
  'Cybersecurity Analyst',
  'Product Manager',
  'Technical Product Manager',
  'Project Manager',
  'Engineering Manager',
  'Technical Lead',
  'VP of Engineering',
  'CTO',
  'UX Designer',
  'UI Designer',
  'Product Designer',
  'UX Researcher',
  'Graphic Designer',
  'Business Analyst',
  'Systems Analyst',
  'Systems Administrator',
  'Database Administrator',
  'Network Engineer',
  'Technical Writer',
  'Solutions Architect',
  'Cloud Architect',
  'Enterprise Architect',
  'Scrum Master',
  'Agile Coach',
  'IT Support Specialist',
  'Help Desk Technician',
  'Embedded Systems Engineer',
  'Firmware Engineer',
  'Game Developer',
  'Blockchain Developer',
];

export const COMPANIES = [
  'Google',
  'Microsoft',
  'Amazon',
  'Apple',
  'Meta',
  'Netflix',
  'Spotify',
  'Stripe',
  'Airbnb',
  'Uber',
  'Lyft',
  'Shopify',
  'Slack',
  'Salesforce',
  'Adobe',
  'Oracle',
  'IBM',
  'Intel',
  'Nvidia',
  'AMD',
  'Tesla',
  'SpaceX',
  'Palantir',
  'Snowflake',
  'Databricks',
  'Datadog',
  'Cloudflare',
  'Twilio',
  'Square',
  'Block',
  'Coinbase',
  'Robinhood',
  'Plaid',
  'GitHub',
  'GitLab',
  'Atlassian',
  'Notion',
  'Figma',
  'Canva',
  'Vercel',
  'Supabase',
  'MongoDB',
  'Elastic',
  'Redis',
  'Docker',
  'HashiCorp',
  'Confluent',
  'Okta',
  'CrowdStrike',
  'Palo Alto Networks',
  'ServiceNow',
  'Workday',
  'SAP',
  'Intuit',
  'PayPal',
  'Visa',
  'Mastercard',
  'JPMorgan Chase',
  'Goldman Sachs',
  'Morgan Stanley',
  'TD Bank',
  'RBC',
  'BMO',
  'Scotiabank',
  'CIBC',
  'Deloitte',
  'McKinsey',
  'BCG',
  'Accenture',
  'Capgemini',
  'Cognizant',
  'Infosys',
  'TCS',
  'Wipro',
  'Samsung',
  'Sony',
  'Siemens',
  'Cisco',
  'Dell',
  'HP',
  'Lenovo',
];

export const LOCATIONS = [
  'Toronto, Canada',
  'Vancouver, Canada',
  'Montreal, Canada',
  'Ottawa, Canada',
  'Calgary, Canada',
  'Edmonton, Canada',
  'Winnipeg, Canada',
  'Halifax, Canada',
  'Waterloo, Canada',
  'Mississauga, Canada',
  'New York, USA',
  'San Francisco, USA',
  'San Jose, USA',
  'Seattle, USA',
  'Austin, USA',
  'Boston, USA',
  'Chicago, USA',
  'Los Angeles, USA',
  'Denver, USA',
  'Atlanta, USA',
  'Dallas, USA',
  'Houston, USA',
  'Miami, USA',
  'Washington DC, USA',
  'Philadelphia, USA',
  'Portland, USA',
  'Minneapolis, USA',
  'Raleigh, USA',
  'San Diego, USA',
  'Phoenix, USA',
  'London, UK',
  'Manchester, UK',
  'Edinburgh, UK',
  'Birmingham, UK',
  'Bristol, UK',
  'Cambridge, UK',
  'Oxford, UK',
  'Sydney, Australia',
  'Melbourne, Australia',
  'Brisbane, Australia',
  'Perth, Australia',
  'Berlin, Germany',
  'Munich, Germany',
  'Hamburg, Germany',
  'Frankfurt, Germany',
  'Paris, France',
  'Lyon, France',
  'Amsterdam, Netherlands',
  'Dublin, Ireland',
  'Zurich, Switzerland',
  'Stockholm, Sweden',
  'Copenhagen, Denmark',
  'Oslo, Norway',
  'Helsinki, Finland',
  'Barcelona, Spain',
  'Madrid, Spain',
  'Lisbon, Portugal',
  'Singapore',
  'Tokyo, Japan',
  'Bangalore, India',
  'Hyderabad, India',
  'Mumbai, India',
  'Tel Aviv, Israel',
];
